@baseUrl = http://localhost:3000

### Sugestão de Produtos para serem feitos
GET {{baseUrl}}/products/suggestion


# MATERIALS CRUD

### Listar todos os materiais
GET {{baseUrl}}/materials

### Criar um novo material (Ex: Couro Sintético)
POST {{baseUrl}}/materials
Content-Type: application/json

{
  "name": "Couro Sintético Premium (m)",
  "stock": 50.0
}

### Atualizar material 
PATCH {{baseUrl}}/materials/83a2f50d-23d4-41ed-9418-dad4925f787b
Content-Type: application/json

{
  "stock": 200.0
}

### Deletar material
DELETE {{baseUrl}}/materials/14d33e88-b4a2-4ce0-a891-62391d8c182c

# PRODUCTS CRUD

### Listar todos os produtos
GET {{baseUrl}}/products

### Criar um novo produto 
POST {{baseUrl}}/products
Content-Type: application/json

{
  "name": "Bone Streetwear Limited Edition",
  "price": 85.90,
  "materials": [
    {
      "materialId": "58189e23-6aeb-41ea-960f-438a08384801", 
      "quantity": 0.3
    },
    {
      "materialId": "2e8c117f-6c42-47a9-a2c9-a0bef470dbee", 
      "quantity": 1.0
    }
  ]
}

### Atualizar produto (Troque o ID)
PATCH {{baseUrl}}/products/84fcb59c-3fda-45f5-9ad4-ed9ee58272af
Content-Type: application/json

{
  "price": 109.90,
  "materials": []
}

### Deletar produto
DELETE {{baseUrl}}/products/4bc5b609-3fa4-4d2e-a41a-db606b886085